subinclude('//android')

android_project(
    name = 'aaudio_common',
    library = True,
    deps = [
        '//third_party/android:support-annotations',
    ],
    visibility = ['//android/example2/aaudio/...'],
)
