cc_library(
    name = "unittest_main",
    srcs = ["unittest_main.cc"],
    visibility = ["PUBLIC"],
    deps = ["///third_party/cc/unittest_cpp"],
)

filegroup(
    name = "thinlto",
    srcs = ["thinlto.build_defs"],
    visibility = ["PUBLIC"],
)
