filegroup(
    name = "maven_library",
    srcs = ["maven_library.build_defs"],
    visibility = ["PUBLIC"],
)

filegroup(
    name = "maven_jars",
    srcs = ["maven_jars.build_defs"],
    visibility = ["PUBLIC"],
)
