# Rules related to protocol buffers and gRPC.

filegroup(
    name = 'grpc_gateway',
    srcs = ['grpc_gateway.build_defs'],
    visibility = ['PUBLIC'],
)

# this is a fork of the original rules that exist in please 
filegroup(
    name = 'proto',
    srcs = ['proto_rules.build_defs'],
    visibility = ['PUBLIC'],
)