# Extra build rules for Go.

filegroup(
    name = 'go_bindata',
    srcs = ['go_bindata.build_defs'],
    visibility = ['PUBLIC'],
)

filegroup(
    name = 'go_yacc',
    srcs = ['go_yacc.build_defs'],
    visibility = ['PUBLIC'],
)
