# Extra build rules for Go.

filegroup(
    name = 'go_bindata',
    srcs = ['go_bindata.build_defs'],
    visibility = ['PUBLIC'],
)

filegroup(
    name = 'go_generate',
    srcs = ['go_generate.build_defs'],
    visibility = ['PUBLIC'],
)
