apiVersion: v1
kind: Service
metadata:
  name: example
  labels:
    app: example
    project: please
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
  selector:
    app: example
