filegroup(
    name = 'webpack_config',
    srcs = ['config.js'],
    deps = [
        '//third_party/js:babel-loader',
        '//third_party/js:babel-preset-es2015',
        '//third_party/js:babel-preset-react',
        '//third_party/js:webpack',
        '//third_party/js:webpack-closure-compiler',
    ],
    visibility = ['PUBLIC'],
)
