filegroup(
    name = 'webpack_config',
    srcs = ['config.js'],
    deps = [
        '//third_party/js:webpack',
        '//third_party/js:webpack-closure-compiler',
    ],
    visibility = ['PUBLIC'],
)
